### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by 0shaurya** [0shaurya/mathular#3]
Add:

**Algebra**:
- [ ] Inequalities
- [ ] Solving Word Problems

**Geometry**:
- [ ] Perpendicular Lines
- [ ] Polygons
- [ ] Convex vs. Concave Polygons
- [ ] Medians and Altitudes

**Precalculus**:
- [ ] Domain and Range
- [ ] Rational Functions
- [ ] Factoring
- [ ] Asymptotes and Discontinuities
- [ ] Polar
- [ ] Combinations and Permutations

**Calculus**:
- [ ] Concavity
- [ ] First/second order derivatives
- [ ] Riemann Sums
- [ ] Accumulation
- [ ] Related Rates
- [ ] Differential Equations
- [ ] Revolutions
